select * from sys.dm_os_waiting_tasks w
where 
	w.wait_type not in ('WAITFOR', 'LAZYWRITER_SLEEP', 'KSOURCE_WAKEUP', 'SLEEP_TASK', 'XE_TIMER_EVENT',
	'BROKER_TRANSMITTER', 'BROKER_RECEIVE_WAITFOR', 'BROKER_EVENTHANDLER', 'BROKER_TASK_STOP', 'BROKER_TO_FLUSH',
	'CLR_MANUAL_EVENT', 'CLR_AUTO_EVENT', 'XE_DISPATCHER_WAIT', 'REQUEST_FOR_DEADLOCK_SEARCH', 
	'ONDEMAND_TASK_QUEUE', 'SQLTRACE_INCREMENTAL_FLUSH_SLEEP')
	and w.wait_type not in ('FSAGENT') -- cmd-висяки
order by w.wait_duration_ms desc