  DECLARE @SQL varchar(max), @DataBase sysname
  SET @DataBase = 'MicexGate_testRobot'

  SET @SQL = '
  ALTER DATABASE ' + QuoteName(@DataBase) + ' SET
  ANSI_NULLS ON,
  ANSI_NULL_DEFAULT ON,
  ANSI_PADDING ON,
  ANSI_WARNINGS ON,
  ARITHABORT ON,
  CONCAT_NULL_YIELDS_NULL ON,
  QUOTED_IDENTIFIER ON,
  CURSOR_DEFAULT LOCAL,
  --ALLOW_SNAPSHOT_ISOLATION ON,
  READ_COMMITTED_SNAPSHOT ON,
  DB_CHAINING ON, 
  TRUSTWORTHY ON
--  , ENABLE_BROKER
  WITH ROLLBACK IMMEDIATE
'
  EXEC(@SQL)

  --SET @SQL = 'ALTER DATABASE ' + QuoteName(@DataBase) + ' SET NEW_BROKER WITH ROLLBACK IMMEDIATE'
  --SET @SQL = 'ALTER DATABASE ' + QuoteName(@DataBase) + ' SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE'
  --EXEC(@SQL)
